import type { CommandRunner } from './command-runner.js';
import type {
  CiState,
  PrHandoffPacket,
  PullRequestContext,
  PullRequestDiff,
  PullRequestCreationInput,
  RepositoryContext,
  ReviewCommentInput,
  CiWaitOptions,
} from './types.js';

interface GhPrView {
  number: number;
  title: string;
  url: string;
  headRefName: string;
  baseRefName: string;
  headRefOid: string;
  baseRefOid: string;
  body?: string;
  author?: { login?: string };
  statusCheckRollup?: Array<{ conclusion?: string; status?: string; state?: string }>;
  comments?: Array<{ body?: string }>;
}

interface GhFile {
  path: string;
  additions: number;
  deletions: number;
}

function deriveCiState(checks: GhPrView['statusCheckRollup']): CiState {
  if (!checks || checks.length === 0) return 'UNKNOWN';

  const values = checks.map((check) =>
    String(check.conclusion || check.status || check.state || '').toUpperCase(),
  );

  if (values.some((value) => ['FAILURE', 'ERROR', 'CANCELLED', 'TIMED_OUT'].includes(value))) {
    return 'FAILURE';
  }
  if (values.some((value) => ['PENDING', 'QUEUED', 'IN_PROGRESS', 'EXPECTED'].includes(value))) {
    return 'PENDING';
  }
  if (values.every((value) => ['SUCCESS', 'NEUTRAL', 'SKIPPED'].includes(value))) {
    return 'SUCCESS';
  }
  return 'UNKNOWN';
}

export class CiWaitTimeoutError extends Error {
  constructor(readonly prNumber: number, readonly timeoutMs: number) {
    super(`Timed out after ${timeoutMs}ms waiting for CI on PR #${prNumber}.`);
    this.name = 'CiWaitTimeoutError';
  }
}

export interface GitHubClientOptions {
  sleep?: (milliseconds: number) => Promise<void>;
  now?: () => number;
}

function reviewMarker(input: ReviewCommentInput): string {
  return `<!-- ai-workflow:${input.phase}:${input.iteration}:${input.headSha} -->`;
}

export function renderReviewComment(input: ReviewCommentInput): string {
  const issues = input.issues.length === 0
    ? '- No issues.'
    : input.issues.map((issue) => {
        const location = issue.file
          ? ` (${issue.file}${issue.line ? `:${issue.line}` : ''})`
          : '';
        const fix = issue.recommendedFix ? `\n  - Suggested fix: ${issue.recommendedFix}` : '';
        return `- **${issue.severity} ${issue.id}**${location}: ${issue.problem}${fix}`;
      }).join('\n');
  return [
    reviewMarker(input),
    `## AI Workflow ${input.phase === 'clean-room' ? 'Clean-room Review' : 'Review'} — iteration ${input.iteration}`,
    '',
    `Verdict: **${input.verdict}**`,
    `Reviewed head: \`${input.headSha}\``,
    '',
    '### Issues',
    issues,
    '',
    '_Generated by ai-workflow. Human approval is still required before merge._',
  ].join('\n');
}

export class GitHubClient {
  private readonly sleep: (milliseconds: number) => Promise<void>;
  private readonly now: () => number;

  constructor(
    private readonly runner: CommandRunner,
    private readonly cwd: string,
    options: GitHubClientOptions = {},
  ) {
    this.sleep = options.sleep ?? ((milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds)));
    this.now = options.now ?? Date.now;
  }

  async getRepository(): Promise<RepositoryContext> {
    const result = await this.runner.run(
      'gh',
      ['repo', 'view', '--json', 'owner,name,defaultBranchRef'],
      this.cwd,
    );
    const data = JSON.parse(result.stdout) as {
      owner: { login: string };
      name: string;
      defaultBranchRef?: { name?: string };
    };
    return {
      owner: data.owner.login,
      name: data.name,
      defaultBranch: data.defaultBranchRef?.name,
    };
  }

  async getPullRequest(prNumber?: number): Promise<PullRequestContext> {
    const args = ['pr', 'view'];
    if (prNumber !== undefined) args.push(String(prNumber));
    args.push(
      '--json',
      'number,title,url,headRefName,baseRefName,headRefOid,baseRefOid,body,author,statusCheckRollup',
    );

    const result = await this.runner.run('gh', args, this.cwd);
    const data = JSON.parse(result.stdout) as GhPrView;

    return {
      number: data.number,
      title: data.title,
      url: data.url,
      headRefName: data.headRefName,
      baseRefName: data.baseRefName,
      headSha: data.headRefOid,
      baseSha: data.baseRefOid,
      body: data.body,
      author: data.author?.login,
      ciState: deriveCiState(data.statusCheckRollup),
    };
  }

  async getPullRequestDiff(prNumber: number): Promise<PullRequestDiff> {
    const [diffResult, filesResult] = await Promise.all([
      this.runner.run('gh', ['pr', 'diff', String(prNumber)], this.cwd),
      this.runner.run('gh', ['pr', 'view', String(prNumber), '--json', 'files'], this.cwd),
    ]);

    const fileData = JSON.parse(filesResult.stdout) as { files: GhFile[] };
    return {
      patch: diffResult.stdout,
      files: fileData.files.map((file) => ({
        path: file.path,
        additions: file.additions,
        deletions: file.deletions,
      })),
    };
  }

  async createHandoffPacket(prNumber?: number): Promise<PrHandoffPacket> {
    const repository = await this.getRepository();
    const pullRequest = await this.getPullRequest(prNumber);
    const diff = await this.getPullRequestDiff(pullRequest.number);

    return {
      repository,
      pullRequest,
      diff,
      generatedAt: new Date().toISOString(),
    };
  }

  async assertCleanWorktree(): Promise<void> {
    const result = await this.runner.run(
      'git',
      ['status', '--porcelain', '--untracked-files=all'],
      this.cwd,
    );
    const nonWorkflowChanges = result.stdout
      .split('\n')
      .filter(Boolean)
      .filter((line) => {
        const path = line.slice(3).replace(/^"|"$/g, '');
        return path !== '.ai' && !path.startsWith('.ai/');
      });
    if (nonWorkflowChanges.length > 0) {
      throw new Error('Workflow requires a clean worktree before creating or switching branches.');
    }
  }

  async getCurrentBranch(): Promise<string> {
    return (await this.runner.run('git', ['branch', '--show-current'], this.cwd)).stdout.trim();
  }

  async prepareBranch(branch: string, baseBranch: string): Promise<string> {
    if (!branch.trim()) throw new Error('Branch name is required.');
    await this.assertCleanWorktree();
    const current = await this.getCurrentBranch();
    if (current === branch) return current;

    const existing = await this.runner.run('git', ['branch', '--list', branch], this.cwd);
    if (existing.stdout.trim()) {
      await this.runner.run('git', ['switch', branch], this.cwd);
    } else {
      await this.runner.run('git', ['switch', '-c', branch, baseBranch], this.cwd);
    }
    return branch;
  }

  async pushBranch(branch: string): Promise<void> {
    if (!branch.trim()) throw new Error('Cannot push an empty branch name.');
    await this.runner.run('git', ['push', '--set-upstream', 'origin', branch], this.cwd);
  }

  async ensurePullRequest(input: PullRequestCreationInput): Promise<PullRequestContext> {
    const repository = await this.getRepository();
    const slug = `${repository.owner}/${repository.name}`;
    const existing = await this.runner.run(
      'gh',
      ['pr', 'list', '--head', input.headBranch, '--state', 'open', '--json', 'number', '-R', slug],
      this.cwd,
    );
    const matches = JSON.parse(existing.stdout) as Array<{ number: number }>;
    if (matches[0]) return this.getPullRequest(matches[0].number);

    const created = await this.runner.run(
      'gh',
      [
        'pr', 'create', '--head', input.headBranch, '--base', input.baseBranch,
        '--title', input.title, '--body', input.body, '-R', slug,
      ],
      this.cwd,
    );
    const match = created.stdout.match(/\/pull\/(\d+)/);
    if (!match?.[1]) throw new Error(`Could not determine created PR number from: ${created.stdout}`);
    return this.getPullRequest(Number.parseInt(match[1], 10));
  }

  async waitForCi(prNumber: number, options: CiWaitOptions): Promise<PullRequestContext> {
    if (options.timeoutMs <= 0 || options.pollIntervalMs <= 0) {
      throw new Error('CI timeout and poll interval must be positive.');
    }
    const startedAt = this.now();
    while (true) {
      const pullRequest = await this.getPullRequest(prNumber);
      if (pullRequest.ciState === 'SUCCESS' || pullRequest.ciState === 'FAILURE') {
        return pullRequest;
      }
      const elapsed = this.now() - startedAt;
      if (elapsed >= options.timeoutMs) throw new CiWaitTimeoutError(prNumber, options.timeoutMs);
      await this.sleep(Math.min(options.pollIntervalMs, options.timeoutMs - elapsed));
    }
  }

  async publishReviewComment(prNumber: number, input: ReviewCommentInput): Promise<boolean> {
    const repository = await this.getRepository();
    const slug = `${repository.owner}/${repository.name}`;
    const marker = reviewMarker(input);
    const current = await this.runner.run(
      'gh',
      ['pr', 'view', String(prNumber), '--json', 'comments', '-R', slug],
      this.cwd,
    );
    const data = JSON.parse(current.stdout) as Pick<GhPrView, 'comments'>;
    if (data.comments?.some((comment) => comment.body?.includes(marker))) return false;

    await this.runner.run(
      'gh',
      ['pr', 'comment', String(prNumber), '--body', renderReviewComment(input), '-R', slug],
      this.cwd,
    );
    return true;
  }
}
