import {
  deterministicChecksPassed,
  hasCommit,
  type AntigravityAdapter,
  type TaskContract,
} from '../adapters/antigravity/index.js';
import type { GitHubClient, PullRequestContext } from '../github/index.js';
import type { StateStore, WorkflowPersistedState } from '../state/index.js';
import { transition } from './workflow-state.js';
import type { ReviewLoopContext, ReviewLoopResult } from './review-loop.js';
import type { ReviewLoopCoordinator } from './review-loop.js';

export interface WorkflowRunInput {
  task: TaskContract;
  branch: string;
  baseBranch: string;
  pullRequestTitle?: string;
  pullRequestBody?: string;
  reviewContext?: ReviewLoopContext;
}

export interface WorkflowRunResult extends ReviewLoopResult {
  prNumber?: number;
  prUrl?: string;
}

export class WorkflowCoordinator {
  constructor(
    private readonly github: GitHubClient,
    private readonly antigravity: AntigravityAdapter,
    private readonly reviewLoop: ReviewLoopCoordinator,
    private readonly stateStore: StateStore,
    private readonly maxLocalFixAttempts = 3,
  ) {
    if (!Number.isInteger(maxLocalFixAttempts) || maxLocalFixAttempts <= 0) {
      throw new Error('maxLocalFixAttempts must be a positive integer.');
    }
  }

  private async save(state: WorkflowPersistedState): Promise<void> {
    await this.stateStore.save(state);
  }

  private async createPullRequest(
    input: WorkflowRunInput,
    state: WorkflowPersistedState,
  ): Promise<PullRequestContext> {
    await this.github.pushBranch(input.branch);
    const pullRequest = await this.github.ensurePullRequest({
      headBranch: input.branch,
      baseBranch: input.baseBranch,
      title: input.pullRequestTitle ?? `${input.task.task.id}: ${input.task.task.objective}`,
      body: input.pullRequestBody ?? [
        `Automated implementation for ${input.task.task.id}.`,
        '',
        '## Objective',
        input.task.task.objective,
        '',
        '## Acceptance criteria',
        ...input.task.task.acceptanceCriteria.map((criterion) => `- ${criterion}`),
        '',
        '_Generated by ai-workflow. Merge requires human approval._',
      ].join('\n'),
    });
    state.prNumber = pullRequest.number;
    state.state = transition(state.state, 'PR_CREATED');
    await this.save(state);
    return pullRequest;
  }

  private async resumeFix(
    input: WorkflowRunInput,
    state: WorkflowPersistedState,
  ): Promise<boolean> {
    const openIssues = Object.values(state.issues)
      .filter((issue) => issue.status === 'OPEN' && (issue.severity === 'P0' || issue.severity === 'P1'))
      .map((issue) => ({
        id: issue.id,
        severity: issue.severity,
        problem: issue.problem ?? 'Resolve the persisted blocking workflow issue.',
        recommendedFix: issue.recommendedFix,
      }));
    if (openIssues.length === 0) {
      state.state = transition(state.state, 'NEEDS_HUMAN');
      await this.save(state);
      return false;
    }

    const execution = await this.antigravity.fix(input.task, openIssues);
    state.state = transition(state.state, 'TESTING');
    const ready = deterministicChecksPassed(execution) && hasCommit(execution);
    if (!ready) state.state = transition(state.state, 'FIXING');
    if (ready) {
      for (const issue of Object.values(state.issues)) {
        if (issue.status === 'OPEN' && (issue.severity === 'P0' || issue.severity === 'P1')) {
          issue.status = 'FIXED';
        }
      }
    }
    await this.save(state);
    if (!ready) return false;
    if (!execution.branch) throw new Error('Antigravity fix did not report a branch.');
    await this.github.pushBranch(execution.branch);
    return true;
  }

  async run(input: WorkflowRunInput): Promise<WorkflowRunResult> {
    const state = await this.stateStore.load();
    if (state.taskId && state.taskId !== input.task.task.id) {
      throw new Error(`State belongs to task ${state.taskId}, not ${input.task.task.id}.`);
    }
    state.taskId = input.task.task.id;

    let pullRequest: PullRequestContext | undefined;
    if (state.state === 'NEW') {
      await this.github.prepareBranch(input.branch, input.baseBranch);
      state.state = transition(state.state, 'CODING');
      await this.save(state);

      let execution;
      try {
        execution = await this.antigravity.implement(input.task);
      } catch (error) {
        state.state = transition(state.state, 'NEEDS_HUMAN');
        await this.save(state);
        throw error;
      }
      state.state = transition(state.state, 'TESTING');
      if (!deterministicChecksPassed(execution) || !hasCommit(execution)) {
        state.issues['LOCAL-CHECKS'] = {
          id: 'LOCAL-CHECKS',
          severity: 'P1',
          status: 'OPEN',
          problem: `Initial implementation did not pass deterministic checks: ${execution.errors.join('; ') || JSON.stringify(execution.checks)}`,
          recommendedFix: 'Inspect the failed local checks, fix the root cause, rerun all checks, and commit the result.',
        };
        state.state = transition(state.state, 'FIXING');
        await this.save(state);
        let fixed = false;
        for (let attempt = 0; attempt < this.maxLocalFixAttempts && !fixed; attempt += 1) {
          fixed = await this.resumeFix(input, state);
        }
        if (!fixed) return { state: state.state, iteration: state.iteration };
      }
      pullRequest = await this.createPullRequest(input, state);
    } else if (state.state === 'FIXING') {
      let fixed = false;
      for (let attempt = 0; attempt < this.maxLocalFixAttempts && !fixed; attempt += 1) {
        fixed = await this.resumeFix(input, state);
      }
      if (!fixed) return { state: state.state, iteration: state.iteration, prNumber: state.prNumber };
    }

    if (state.state === 'CODING' || state.state === 'NEW') {
      throw new Error(`Cannot resume workflow from incomplete state ${state.state}.`);
    }
    if (state.state === 'TESTING' && state.prNumber === undefined) {
      pullRequest = await this.createPullRequest(input, state);
    }

    const prNumber = state.prNumber ?? pullRequest?.number;
    if (prNumber === undefined) {
      if (state.state === 'NEEDS_HUMAN' || state.state === 'MERGED') {
        return { state: state.state, iteration: state.iteration };
      }
      throw new Error('Workflow state does not contain a pull request number.');
    }

    const result = await this.reviewLoop.run(input.task, prNumber, input.reviewContext);
    const currentPr = pullRequest ?? await this.github.getPullRequest(prNumber);
    return { ...result, prNumber, prUrl: currentPr.url };
  }
}
